[package]
name = "imavafe/onyx-ui"
description = "Quick, quality UI for Fusion"
version = "0.2.0"
license = "MIT"
authors = ["Avafe"]

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ColorUtils = "csqrl/colour-utils@1.4.1"
Fusion = "elttob/fusion@0.2.0"
