[package]
name = "avafe/neka-ui"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ColourUtils = "csqrl/colour-utils@1.3.1"
Fusion = "elttob/fusion@0.2.0"